// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api_cinema_challenge.Data;

#nullable disable

namespace api_cinema_challenge.Migrations
{
    [DbContext(typeof(CinemaContext))]
    [Migration("20250825084958_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api_cinema_challenge.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(713),
                            Email = "kate middleton@gov.gr",
                            Name = "Kate Middleton",
                            Phone = "57323012",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(932)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2183),
                            Email = "kate trump@something.com",
                            Name = "Kate Trump",
                            Phone = "90036955",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2183)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2204),
                            Email = "kate winslet@gov.ru",
                            Name = "Kate Winslet",
                            Phone = "79662272",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2208)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2211),
                            Email = "kate winslet@something.com",
                            Name = "Kate Winslet",
                            Phone = "97434122",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2211)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2213),
                            Email = "elvis hendrix@gov.us",
                            Name = "Elvis Hendrix",
                            Phone = "84320894",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2215)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2240),
                            Email = "kate hendrix@gov.ru",
                            Name = "Kate Hendrix",
                            Phone = "86093045",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2241)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2242),
                            Email = "jimi trump@google.com",
                            Name = "Jimi Trump",
                            Phone = "77608896",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2243)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2244),
                            Email = "kate hendrix@gov.nl",
                            Name = "Kate Hendrix",
                            Phone = "30950692",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2245)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2246),
                            Email = "charles hepburn@google.com",
                            Name = "Charles Hepburn",
                            Phone = "53960475",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2246)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2249),
                            Email = "barack obama@gov.nl",
                            Name = "Barack Obama",
                            Phone = "11402717",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2249)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2252),
                            Email = "mick jagger@gov.gr",
                            Name = "Mick Jagger",
                            Phone = "74377263",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2252)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2253),
                            Email = "kate hepburn@tesla.com",
                            Name = "Kate Hepburn",
                            Phone = "37130689",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2254)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2255),
                            Email = "kate windsor@google.com",
                            Name = "Kate Windsor",
                            Phone = "17850864",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2255)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2257),
                            Email = "donald jagger@tesla.com",
                            Name = "Donald Jagger",
                            Phone = "96174535",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2257)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2259),
                            Email = "barack hendrix@something.com",
                            Name = "Barack Hendrix",
                            Phone = "38010217",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2259)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2260),
                            Email = "elvis winfrey@gov.nl",
                            Name = "Elvis Winfrey",
                            Phone = "68797228",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2260)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2262),
                            Email = "mick middleton@something.com",
                            Name = "Mick Middleton",
                            Phone = "55871184",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2262)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2265),
                            Email = "elvis obama@nasa.org.us",
                            Name = "Elvis Obama",
                            Phone = "99746360",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2266)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2267),
                            Email = "jimi hepburn@gov.gr",
                            Name = "Jimi Hepburn",
                            Phone = "15774057",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2267)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2269),
                            Email = "kate presley@tesla.com",
                            Name = "Kate Presley",
                            Phone = "33030025",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2269)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2270),
                            Email = "mick windsor@theworld.ca",
                            Name = "Mick Windsor",
                            Phone = "68406720",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2270)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2272),
                            Email = "mick windsor@bbc.co.uk",
                            Name = "Mick Windsor",
                            Phone = "70274513",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2272)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2273),
                            Email = "barack windsor@google.com",
                            Name = "Barack Windsor",
                            Phone = "10112351",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2273)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2275),
                            Email = "elvis hendrix@bbc.co.uk",
                            Name = "Elvis Hendrix",
                            Phone = "21340088",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2275)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2276),
                            Email = "barack hendrix@nasa.org.us",
                            Name = "Barack Hendrix",
                            Phone = "67170625",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2276)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2278),
                            Email = "kate winslet@bbc.co.uk",
                            Name = "Kate Winslet",
                            Phone = "86772435",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2278)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2279),
                            Email = "barack obama@bbc.co.uk",
                            Name = "Barack Obama",
                            Phone = "83625317",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2279)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2281),
                            Email = "jimi hepburn@gov.nl",
                            Name = "Jimi Hepburn",
                            Phone = "89412341",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2281)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2293),
                            Email = "mick jagger@gov.nl",
                            Name = "Mick Jagger",
                            Phone = "37434825",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2294)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2295),
                            Email = "barack jagger@gov.ru",
                            Name = "Barack Jagger",
                            Phone = "23194181",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2296)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2297),
                            Email = "elvis winfrey@gov.nl",
                            Name = "Elvis Winfrey",
                            Phone = "54447837",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2297)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2299),
                            Email = "kate winfrey@bbc.co.uk",
                            Name = "Kate Winfrey",
                            Phone = "58976369",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2299)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2300),
                            Email = "charles jagger@something.com",
                            Name = "Charles Jagger",
                            Phone = "22440998",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2301)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2303),
                            Email = "kate middleton@nasa.org.us",
                            Name = "Kate Middleton",
                            Phone = "19231484",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2303)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2304),
                            Email = "oprah jagger@nasa.org.us",
                            Name = "Oprah Jagger",
                            Phone = "96209492",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2305)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2306),
                            Email = "jimi middleton@gov.us",
                            Name = "Jimi Middleton",
                            Phone = "14860055",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2306)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2308),
                            Email = "mick windsor@bbc.co.uk",
                            Name = "Mick Windsor",
                            Phone = "46462376",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2308)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2309),
                            Email = "elvis presley@theworld.ca",
                            Name = "Elvis Presley",
                            Phone = "11443439",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2310)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2311),
                            Email = "donald winfrey@something.com",
                            Name = "Donald Winfrey",
                            Phone = "71902615",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2311)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2313),
                            Email = "charles hepburn@gov.us",
                            Name = "Charles Hepburn",
                            Phone = "42984697",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2313)
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2314),
                            Email = "mick jagger@tesla.com",
                            Name = "Mick Jagger",
                            Phone = "36431777",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2315)
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2316),
                            Email = "jimi hepburn@gov.nl",
                            Name = "Jimi Hepburn",
                            Phone = "93119392",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2316)
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2318),
                            Email = "mick middleton@bbc.co.uk",
                            Name = "Mick Middleton",
                            Phone = "60445327",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2318)
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2319),
                            Email = "jimi winslet@tesla.com",
                            Name = "Jimi Winslet",
                            Phone = "27412326",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2320)
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2321),
                            Email = "audrey windsor@tesla.com",
                            Name = "Audrey Windsor",
                            Phone = "41701761",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2321)
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2322),
                            Email = "kate middleton@gov.nl",
                            Name = "Kate Middleton",
                            Phone = "77306134",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2323)
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2324),
                            Email = "mick hepburn@gov.gr",
                            Name = "Mick Hepburn",
                            Phone = "69932733",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2325)
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2326),
                            Email = "donald winslet@gov.us",
                            Name = "Donald Winslet",
                            Phone = "95603319",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2326)
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2327),
                            Email = "elvis trump@gov.ru",
                            Name = "Elvis Trump",
                            Phone = "75749612",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2328)
                        });
                });

            modelBuilder.Entity("api_cinema_challenge.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("movie_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rating");

                    b.Property<int>("RunTimeMins")
                        .HasColumnType("integer")
                        .HasColumnName("runtime_mins");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("movie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2700),
                            Description = "Very funny",
                            Rating = "years 18+",
                            RunTimeMins = 148,
                            Title = "The Bitter Flowers",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(2811)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(3338),
                            Description = "Very funny",
                            Rating = "years 16+",
                            RunTimeMins = 93,
                            Title = "A bunch of Orange Flowers",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(3339)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(3343),
                            Description = "Very funny",
                            Rating = "years 6+",
                            RunTimeMins = 127,
                            Title = "Several Transparent Buildings",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(3344)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(3346),
                            Description = "Very funny",
                            Rating = "All",
                            RunTimeMins = 70,
                            Title = "A herd of Green Planets",
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(3346)
                        });
                });

            modelBuilder.Entity("api_cinema_challenge.Models.Screening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("screening_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer")
                        .HasColumnName("movie_id");

                    b.Property<int>("ScreenNumber")
                        .HasColumnType("integer")
                        .HasColumnName("screen_number");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("screenings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 89,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(3602),
                            MovieId = 3,
                            ScreenNumber = 0,
                            StartsAt = new DateTime(2025, 7, 19, 18, 15, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(3692)
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 89,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4667),
                            MovieId = 2,
                            ScreenNumber = 0,
                            StartsAt = new DateTime(2025, 8, 1, 11, 30, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4668)
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 57,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4671),
                            MovieId = 2,
                            ScreenNumber = 1,
                            StartsAt = new DateTime(2025, 7, 3, 9, 55, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4671)
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 26,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4672),
                            MovieId = 4,
                            ScreenNumber = 3,
                            StartsAt = new DateTime(2025, 4, 18, 19, 30, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4673)
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 61,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4674),
                            MovieId = 1,
                            ScreenNumber = 0,
                            StartsAt = new DateTime(2025, 5, 14, 16, 45, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4674)
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 54,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4676),
                            MovieId = 4,
                            ScreenNumber = 4,
                            StartsAt = new DateTime(2025, 1, 5, 8, 15, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4677)
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 76,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4686),
                            MovieId = 2,
                            ScreenNumber = 3,
                            StartsAt = new DateTime(2025, 3, 10, 6, 20, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4686)
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 84,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4687),
                            MovieId = 4,
                            ScreenNumber = 1,
                            StartsAt = new DateTime(2025, 6, 22, 13, 40, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4688)
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 83,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4689),
                            MovieId = 2,
                            ScreenNumber = 4,
                            StartsAt = new DateTime(2025, 2, 3, 7, 45, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4689)
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 68,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4690),
                            MovieId = 2,
                            ScreenNumber = 2,
                            StartsAt = new DateTime(2025, 6, 7, 4, 25, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4691)
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 74,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4691),
                            MovieId = 4,
                            ScreenNumber = 0,
                            StartsAt = new DateTime(2025, 3, 25, 15, 50, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4692)
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 45,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4693),
                            MovieId = 1,
                            ScreenNumber = 1,
                            StartsAt = new DateTime(2025, 3, 10, 6, 20, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4693)
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 34,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4694),
                            MovieId = 2,
                            ScreenNumber = 2,
                            StartsAt = new DateTime(2025, 3, 25, 15, 50, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4694)
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 25,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4695),
                            MovieId = 4,
                            ScreenNumber = 0,
                            StartsAt = new DateTime(2025, 6, 7, 4, 25, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4695)
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 67,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4696),
                            MovieId = 4,
                            ScreenNumber = 3,
                            StartsAt = new DateTime(2025, 4, 18, 19, 30, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4696)
                        },
                        new
                        {
                            Id = 16,
                            Capacity = 67,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4697),
                            MovieId = 4,
                            ScreenNumber = 2,
                            StartsAt = new DateTime(2025, 7, 3, 9, 55, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4697)
                        },
                        new
                        {
                            Id = 17,
                            Capacity = 68,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4698),
                            MovieId = 4,
                            ScreenNumber = 0,
                            StartsAt = new DateTime(2025, 7, 19, 18, 15, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4698)
                        },
                        new
                        {
                            Id = 18,
                            Capacity = 35,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4699),
                            MovieId = 1,
                            ScreenNumber = 1,
                            StartsAt = new DateTime(2025, 8, 1, 11, 30, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4699)
                        },
                        new
                        {
                            Id = 19,
                            Capacity = 72,
                            CreatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4700),
                            MovieId = 4,
                            ScreenNumber = 2,
                            StartsAt = new DateTime(2025, 2, 21, 18, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 8, 49, 55, 411, DateTimeKind.Utc).AddTicks(4700)
                        });
                });

            modelBuilder.Entity("api_cinema_challenge.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ticket_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<int>("ScreeningId")
                        .HasColumnType("integer")
                        .HasColumnName("screening_id");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ScreeningId");

                    b.ToTable("tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 28,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 32,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 21,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 10,
                            ScreeningId = 17
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 19,
                            ScreeningId = 3
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = 34,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 7,
                            CustomerId = 25,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 8,
                            CustomerId = 40,
                            ScreeningId = 6
                        },
                        new
                        {
                            Id = 9,
                            CustomerId = 18,
                            ScreeningId = 17
                        },
                        new
                        {
                            Id = 10,
                            CustomerId = 2,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 11,
                            CustomerId = 41,
                            ScreeningId = 10
                        },
                        new
                        {
                            Id = 12,
                            CustomerId = 17,
                            ScreeningId = 11
                        },
                        new
                        {
                            Id = 13,
                            CustomerId = 11,
                            ScreeningId = 10
                        },
                        new
                        {
                            Id = 14,
                            CustomerId = 37,
                            ScreeningId = 16
                        },
                        new
                        {
                            Id = 15,
                            CustomerId = 27,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 16,
                            CustomerId = 36,
                            ScreeningId = 16
                        },
                        new
                        {
                            Id = 17,
                            CustomerId = 31,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 18,
                            CustomerId = 1,
                            ScreeningId = 3
                        },
                        new
                        {
                            Id = 19,
                            CustomerId = 22,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 20,
                            CustomerId = 40,
                            ScreeningId = 17
                        },
                        new
                        {
                            Id = 21,
                            CustomerId = 49,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 22,
                            CustomerId = 11,
                            ScreeningId = 3
                        },
                        new
                        {
                            Id = 23,
                            CustomerId = 38,
                            ScreeningId = 17
                        },
                        new
                        {
                            Id = 24,
                            CustomerId = 12,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 25,
                            CustomerId = 3,
                            ScreeningId = 16
                        },
                        new
                        {
                            Id = 26,
                            CustomerId = 11,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 27,
                            CustomerId = 19,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 28,
                            CustomerId = 3,
                            ScreeningId = 13
                        },
                        new
                        {
                            Id = 29,
                            CustomerId = 41,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 30,
                            CustomerId = 42,
                            ScreeningId = 8
                        },
                        new
                        {
                            Id = 31,
                            CustomerId = 28,
                            ScreeningId = 16
                        },
                        new
                        {
                            Id = 32,
                            CustomerId = 48,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 33,
                            CustomerId = 45,
                            ScreeningId = 6
                        },
                        new
                        {
                            Id = 34,
                            CustomerId = 28,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 35,
                            CustomerId = 44,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 36,
                            CustomerId = 37,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 37,
                            CustomerId = 30,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 38,
                            CustomerId = 20,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 39,
                            CustomerId = 39,
                            ScreeningId = 1
                        },
                        new
                        {
                            Id = 40,
                            CustomerId = 14,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 41,
                            CustomerId = 2,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 42,
                            CustomerId = 28,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 43,
                            CustomerId = 25,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 44,
                            CustomerId = 42,
                            ScreeningId = 11
                        },
                        new
                        {
                            Id = 45,
                            CustomerId = 1,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 46,
                            CustomerId = 1,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 47,
                            CustomerId = 1,
                            ScreeningId = 13
                        },
                        new
                        {
                            Id = 48,
                            CustomerId = 38,
                            ScreeningId = 13
                        },
                        new
                        {
                            Id = 49,
                            CustomerId = 6,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 50,
                            CustomerId = 1,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 51,
                            CustomerId = 37,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 52,
                            CustomerId = 33,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 53,
                            CustomerId = 3,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 54,
                            CustomerId = 40,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 55,
                            CustomerId = 9,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 56,
                            CustomerId = 49,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 57,
                            CustomerId = 29,
                            ScreeningId = 17
                        },
                        new
                        {
                            Id = 58,
                            CustomerId = 4,
                            ScreeningId = 1
                        },
                        new
                        {
                            Id = 59,
                            CustomerId = 40,
                            ScreeningId = 19
                        },
                        new
                        {
                            Id = 60,
                            CustomerId = 47,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 61,
                            CustomerId = 22,
                            ScreeningId = 6
                        },
                        new
                        {
                            Id = 62,
                            CustomerId = 34,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 63,
                            CustomerId = 28,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 64,
                            CustomerId = 45,
                            ScreeningId = 8
                        },
                        new
                        {
                            Id = 65,
                            CustomerId = 4,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 66,
                            CustomerId = 47,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 67,
                            CustomerId = 22,
                            ScreeningId = 19
                        },
                        new
                        {
                            Id = 68,
                            CustomerId = 6,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 69,
                            CustomerId = 47,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 70,
                            CustomerId = 17,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 71,
                            CustomerId = 40,
                            ScreeningId = 17
                        },
                        new
                        {
                            Id = 72,
                            CustomerId = 21,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 73,
                            CustomerId = 4,
                            ScreeningId = 13
                        },
                        new
                        {
                            Id = 74,
                            CustomerId = 4,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 75,
                            CustomerId = 41,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 76,
                            CustomerId = 19,
                            ScreeningId = 19
                        },
                        new
                        {
                            Id = 77,
                            CustomerId = 20,
                            ScreeningId = 6
                        },
                        new
                        {
                            Id = 78,
                            CustomerId = 9,
                            ScreeningId = 16
                        },
                        new
                        {
                            Id = 79,
                            CustomerId = 14,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 80,
                            CustomerId = 44,
                            ScreeningId = 17
                        },
                        new
                        {
                            Id = 81,
                            CustomerId = 26,
                            ScreeningId = 17
                        },
                        new
                        {
                            Id = 82,
                            CustomerId = 37,
                            ScreeningId = 1
                        },
                        new
                        {
                            Id = 83,
                            CustomerId = 41,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 84,
                            CustomerId = 8,
                            ScreeningId = 19
                        },
                        new
                        {
                            Id = 85,
                            CustomerId = 46,
                            ScreeningId = 16
                        },
                        new
                        {
                            Id = 86,
                            CustomerId = 38,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 87,
                            CustomerId = 43,
                            ScreeningId = 19
                        },
                        new
                        {
                            Id = 88,
                            CustomerId = 30,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 89,
                            CustomerId = 36,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 90,
                            CustomerId = 6,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 91,
                            CustomerId = 17,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 92,
                            CustomerId = 40,
                            ScreeningId = 6
                        },
                        new
                        {
                            Id = 93,
                            CustomerId = 25,
                            ScreeningId = 8
                        },
                        new
                        {
                            Id = 94,
                            CustomerId = 28,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 95,
                            CustomerId = 19,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 96,
                            CustomerId = 33,
                            ScreeningId = 13
                        },
                        new
                        {
                            Id = 97,
                            CustomerId = 5,
                            ScreeningId = 19
                        },
                        new
                        {
                            Id = 98,
                            CustomerId = 36,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 99,
                            CustomerId = 18,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 100,
                            CustomerId = 43,
                            ScreeningId = 1
                        },
                        new
                        {
                            Id = 101,
                            CustomerId = 19,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 102,
                            CustomerId = 47,
                            ScreeningId = 16
                        },
                        new
                        {
                            Id = 103,
                            CustomerId = 24,
                            ScreeningId = 10
                        },
                        new
                        {
                            Id = 104,
                            CustomerId = 29,
                            ScreeningId = 19
                        },
                        new
                        {
                            Id = 105,
                            CustomerId = 23,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 106,
                            CustomerId = 49,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 107,
                            CustomerId = 26,
                            ScreeningId = 13
                        },
                        new
                        {
                            Id = 108,
                            CustomerId = 17,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 109,
                            CustomerId = 46,
                            ScreeningId = 6
                        },
                        new
                        {
                            Id = 110,
                            CustomerId = 46,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 111,
                            CustomerId = 47,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 112,
                            CustomerId = 31,
                            ScreeningId = 3
                        },
                        new
                        {
                            Id = 113,
                            CustomerId = 48,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 114,
                            CustomerId = 31,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 115,
                            CustomerId = 21,
                            ScreeningId = 8
                        },
                        new
                        {
                            Id = 116,
                            CustomerId = 36,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 117,
                            CustomerId = 8,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 118,
                            CustomerId = 12,
                            ScreeningId = 19
                        },
                        new
                        {
                            Id = 119,
                            CustomerId = 42,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 120,
                            CustomerId = 13,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 121,
                            CustomerId = 16,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 122,
                            CustomerId = 30,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 123,
                            CustomerId = 13,
                            ScreeningId = 17
                        },
                        new
                        {
                            Id = 124,
                            CustomerId = 28,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 125,
                            CustomerId = 8,
                            ScreeningId = 8
                        },
                        new
                        {
                            Id = 126,
                            CustomerId = 8,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 127,
                            CustomerId = 38,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 128,
                            CustomerId = 21,
                            ScreeningId = 10
                        },
                        new
                        {
                            Id = 129,
                            CustomerId = 34,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 130,
                            CustomerId = 13,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 131,
                            CustomerId = 34,
                            ScreeningId = 16
                        },
                        new
                        {
                            Id = 132,
                            CustomerId = 29,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 133,
                            CustomerId = 5,
                            ScreeningId = 16
                        },
                        new
                        {
                            Id = 134,
                            CustomerId = 4,
                            ScreeningId = 3
                        },
                        new
                        {
                            Id = 135,
                            CustomerId = 30,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 136,
                            CustomerId = 48,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 137,
                            CustomerId = 49,
                            ScreeningId = 1
                        },
                        new
                        {
                            Id = 138,
                            CustomerId = 38,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 139,
                            CustomerId = 29,
                            ScreeningId = 6
                        },
                        new
                        {
                            Id = 140,
                            CustomerId = 5,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 141,
                            CustomerId = 12,
                            ScreeningId = 8
                        },
                        new
                        {
                            Id = 142,
                            CustomerId = 2,
                            ScreeningId = 13
                        },
                        new
                        {
                            Id = 143,
                            CustomerId = 7,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 144,
                            CustomerId = 9,
                            ScreeningId = 16
                        },
                        new
                        {
                            Id = 145,
                            CustomerId = 26,
                            ScreeningId = 13
                        },
                        new
                        {
                            Id = 146,
                            CustomerId = 14,
                            ScreeningId = 11
                        },
                        new
                        {
                            Id = 147,
                            CustomerId = 49,
                            ScreeningId = 3
                        },
                        new
                        {
                            Id = 148,
                            CustomerId = 17,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 149,
                            CustomerId = 3,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 150,
                            CustomerId = 17,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 151,
                            CustomerId = 19,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 152,
                            CustomerId = 8,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 153,
                            CustomerId = 8,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 154,
                            CustomerId = 16,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 155,
                            CustomerId = 23,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 156,
                            CustomerId = 2,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 157,
                            CustomerId = 34,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 158,
                            CustomerId = 18,
                            ScreeningId = 16
                        },
                        new
                        {
                            Id = 159,
                            CustomerId = 9,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 160,
                            CustomerId = 37,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 161,
                            CustomerId = 27,
                            ScreeningId = 17
                        },
                        new
                        {
                            Id = 162,
                            CustomerId = 26,
                            ScreeningId = 3
                        },
                        new
                        {
                            Id = 163,
                            CustomerId = 34,
                            ScreeningId = 11
                        },
                        new
                        {
                            Id = 164,
                            CustomerId = 4,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 165,
                            CustomerId = 26,
                            ScreeningId = 10
                        },
                        new
                        {
                            Id = 166,
                            CustomerId = 2,
                            ScreeningId = 6
                        },
                        new
                        {
                            Id = 167,
                            CustomerId = 2,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 168,
                            CustomerId = 20,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 169,
                            CustomerId = 18,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 170,
                            CustomerId = 49,
                            ScreeningId = 11
                        },
                        new
                        {
                            Id = 171,
                            CustomerId = 24,
                            ScreeningId = 11
                        },
                        new
                        {
                            Id = 172,
                            CustomerId = 11,
                            ScreeningId = 11
                        },
                        new
                        {
                            Id = 173,
                            CustomerId = 20,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 174,
                            CustomerId = 6,
                            ScreeningId = 11
                        },
                        new
                        {
                            Id = 175,
                            CustomerId = 47,
                            ScreeningId = 13
                        },
                        new
                        {
                            Id = 176,
                            CustomerId = 18,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 177,
                            CustomerId = 1,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 178,
                            CustomerId = 29,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 179,
                            CustomerId = 21,
                            ScreeningId = 11
                        },
                        new
                        {
                            Id = 180,
                            CustomerId = 14,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 181,
                            CustomerId = 22,
                            ScreeningId = 6
                        },
                        new
                        {
                            Id = 182,
                            CustomerId = 33,
                            ScreeningId = 10
                        },
                        new
                        {
                            Id = 183,
                            CustomerId = 34,
                            ScreeningId = 6
                        },
                        new
                        {
                            Id = 184,
                            CustomerId = 35,
                            ScreeningId = 8
                        },
                        new
                        {
                            Id = 185,
                            CustomerId = 27,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 186,
                            CustomerId = 34,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 187,
                            CustomerId = 31,
                            ScreeningId = 3
                        },
                        new
                        {
                            Id = 188,
                            CustomerId = 39,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 189,
                            CustomerId = 22,
                            ScreeningId = 3
                        },
                        new
                        {
                            Id = 190,
                            CustomerId = 3,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 191,
                            CustomerId = 42,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 192,
                            CustomerId = 47,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 193,
                            CustomerId = 5,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 194,
                            CustomerId = 3,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 195,
                            CustomerId = 26,
                            ScreeningId = 19
                        },
                        new
                        {
                            Id = 196,
                            CustomerId = 44,
                            ScreeningId = 8
                        },
                        new
                        {
                            Id = 197,
                            CustomerId = 29,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 198,
                            CustomerId = 30,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 199,
                            CustomerId = 2,
                            ScreeningId = 8
                        });
                });

            modelBuilder.Entity("api_cinema_challenge.Models.Screening", b =>
                {
                    b.HasOne("api_cinema_challenge.Models.Movie", "Movie")
                        .WithMany("Screenings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("api_cinema_challenge.Models.Ticket", b =>
                {
                    b.HasOne("api_cinema_challenge.Models.Customer", "Customer")
                        .WithMany("Tickets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api_cinema_challenge.Models.Screening", "Screening")
                        .WithMany("Tickets")
                        .HasForeignKey("ScreeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Screening");
                });

            modelBuilder.Entity("api_cinema_challenge.Models.Customer", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("api_cinema_challenge.Models.Movie", b =>
                {
                    b.Navigation("Screenings");
                });

            modelBuilder.Entity("api_cinema_challenge.Models.Screening", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
