// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api_cinema_challenge.Data;

#nullable disable

namespace api_cinema_challenge.Migrations
{
    [DbContext(typeof(CinemaContext))]
    [Migration("20250825131522_Test")]
    partial class Test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api_cinema_challenge.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("api_cinema_challenge.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(2035),
                            Email = "audrey hepburn@gov.gr",
                            Name = "Audrey Hepburn",
                            Phone = "24634684",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(2268)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3539),
                            Email = "kate hepburn@bbc.co.uk",
                            Name = "Kate Hepburn",
                            Phone = "49646097",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3540)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3563),
                            Email = "charles presley@gov.nl",
                            Name = "Charles Presley",
                            Phone = "26639659",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3563)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3565),
                            Email = "donald hendrix@gov.ru",
                            Name = "Donald Hendrix",
                            Phone = "65109755",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3566)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3568),
                            Email = "oprah middleton@gov.us",
                            Name = "Oprah Middleton",
                            Phone = "43044406",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3568)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3579),
                            Email = "kate trump@bbc.co.uk",
                            Name = "Kate Trump",
                            Phone = "52083056",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3579)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3581),
                            Email = "charles winfrey@google.com",
                            Name = "Charles Winfrey",
                            Phone = "85242581",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3581)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3604),
                            Email = "donald windsor@gov.us",
                            Name = "Donald Windsor",
                            Phone = "57665393",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3605)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3606),
                            Email = "kate obama@google.com",
                            Name = "Kate Obama",
                            Phone = "22385849",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3607)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3609),
                            Email = "donald windsor@something.com",
                            Name = "Donald Windsor",
                            Phone = "62639816",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3609)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3611),
                            Email = "charles hepburn@gov.ru",
                            Name = "Charles Hepburn",
                            Phone = "62276921",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3611)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3613),
                            Email = "elvis winfrey@tesla.com",
                            Name = "Elvis Winfrey",
                            Phone = "35293476",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3613)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3614),
                            Email = "elvis hepburn@gov.us",
                            Name = "Elvis Hepburn",
                            Phone = "84876191",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3615)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3616),
                            Email = "charles jagger@gov.ru",
                            Name = "Charles Jagger",
                            Phone = "54864917",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3616)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3618),
                            Email = "barack winfrey@gov.ru",
                            Name = "Barack Winfrey",
                            Phone = "34106523",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3618)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3619),
                            Email = "mick windsor@gov.gr",
                            Name = "Mick Windsor",
                            Phone = "52226638",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3619)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3621),
                            Email = "elvis hepburn@nasa.org.us",
                            Name = "Elvis Hepburn",
                            Phone = "50058133",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3621)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3623),
                            Email = "jimi jagger@gov.us",
                            Name = "Jimi Jagger",
                            Phone = "30126005",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3623)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3624),
                            Email = "kate jagger@nasa.org.us",
                            Name = "Kate Jagger",
                            Phone = "28409903",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3625)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3626),
                            Email = "kate jagger@something.com",
                            Name = "Kate Jagger",
                            Phone = "27803251",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3626)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3627),
                            Email = "barack winslet@bbc.co.uk",
                            Name = "Barack Winslet",
                            Phone = "56314127",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3628)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3629),
                            Email = "jimi presley@tesla.com",
                            Name = "Jimi Presley",
                            Phone = "51246437",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3629)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3630),
                            Email = "kate winslet@something.com",
                            Name = "Kate Winslet",
                            Phone = "12062719",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3631)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3632),
                            Email = "mick presley@gov.ru",
                            Name = "Mick Presley",
                            Phone = "84330792",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3633)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3634),
                            Email = "kate hepburn@tesla.com",
                            Name = "Kate Hepburn",
                            Phone = "60705909",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3634)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3635),
                            Email = "kate winslet@nasa.org.us",
                            Name = "Kate Winslet",
                            Phone = "47374763",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3636)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3637),
                            Email = "audrey presley@gov.us",
                            Name = "Audrey Presley",
                            Phone = "89646824",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3637)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3638),
                            Email = "jimi hepburn@gov.gr",
                            Name = "Jimi Hepburn",
                            Phone = "70843563",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3639)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3640),
                            Email = "mick windsor@nasa.org.us",
                            Name = "Mick Windsor",
                            Phone = "21891104",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3640)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3641),
                            Email = "donald trump@nasa.org.us",
                            Name = "Donald Trump",
                            Phone = "77180744",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3642)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3648),
                            Email = "kate presley@gov.nl",
                            Name = "Kate Presley",
                            Phone = "18549554",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3649)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3651),
                            Email = "kate winslet@tesla.com",
                            Name = "Kate Winslet",
                            Phone = "22886454",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3651)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3652),
                            Email = "elvis winfrey@something.com",
                            Name = "Elvis Winfrey",
                            Phone = "44923720",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3653)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3655),
                            Email = "kate winfrey@gov.nl",
                            Name = "Kate Winfrey",
                            Phone = "52713833",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3655)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3656),
                            Email = "jimi hendrix@gov.nl",
                            Name = "Jimi Hendrix",
                            Phone = "69254646",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3656)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3658),
                            Email = "barack trump@tesla.com",
                            Name = "Barack Trump",
                            Phone = "18571321",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3658)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3659),
                            Email = "elvis middleton@bbc.co.uk",
                            Name = "Elvis Middleton",
                            Phone = "66441056",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3659)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3661),
                            Email = "jimi middleton@bbc.co.uk",
                            Name = "Jimi Middleton",
                            Phone = "31023577",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3661)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3663),
                            Email = "kate hendrix@gov.ru",
                            Name = "Kate Hendrix",
                            Phone = "22668985",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3663)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3664),
                            Email = "kate hepburn@theworld.ca",
                            Name = "Kate Hepburn",
                            Phone = "54717904",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3664)
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3666),
                            Email = "elvis jagger@tesla.com",
                            Name = "Elvis Jagger",
                            Phone = "72683693",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3666)
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3667),
                            Email = "barack middleton@nasa.org.us",
                            Name = "Barack Middleton",
                            Phone = "23610983",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3667)
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3669),
                            Email = "kate obama@bbc.co.uk",
                            Name = "Kate Obama",
                            Phone = "28499438",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3669)
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3670),
                            Email = "elvis middleton@gov.ru",
                            Name = "Elvis Middleton",
                            Phone = "39411817",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3671)
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3672),
                            Email = "jimi jagger@gov.us",
                            Name = "Jimi Jagger",
                            Phone = "54613053",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3672)
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3674),
                            Email = "oprah presley@bbc.co.uk",
                            Name = "Oprah Presley",
                            Phone = "80862726",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3674)
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3675),
                            Email = "jimi obama@nasa.org.us",
                            Name = "Jimi Obama",
                            Phone = "20418161",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3675)
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3677),
                            Email = "charles hepburn@theworld.ca",
                            Name = "Charles Hepburn",
                            Phone = "17586489",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3677)
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3678),
                            Email = "oprah middleton@google.com",
                            Name = "Oprah Middleton",
                            Phone = "48095329",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(3678)
                        });
                });

            modelBuilder.Entity("api_cinema_challenge.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("movie_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rating");

                    b.Property<int>("RunTimeMins")
                        .HasColumnType("integer")
                        .HasColumnName("runtime_mins");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("movie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(4071),
                            Description = "Very funny",
                            Rating = "years 11+",
                            RunTimeMins = 129,
                            Title = "A bunch of Large Flowers",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(4202)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(4757),
                            Description = "Very funny",
                            Rating = "All",
                            RunTimeMins = 118,
                            Title = "Several Green Flowers",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(4758)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(4762),
                            Description = "Very funny",
                            Rating = "years 16+",
                            RunTimeMins = 123,
                            Title = "Several Purple Buildings",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(4762)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(4764),
                            Description = "Very funny",
                            Rating = "years 6+",
                            RunTimeMins = 72,
                            Title = "The Bitter Houses",
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(4765)
                        });
                });

            modelBuilder.Entity("api_cinema_challenge.Models.Screening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("screening_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer")
                        .HasColumnName("movie_id");

                    b.Property<int>("ScreenNumber")
                        .HasColumnType("integer")
                        .HasColumnName("screen_number");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("screenings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 77,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(5046),
                            MovieId = 1,
                            ScreenNumber = 0,
                            StartsAt = new DateTime(2025, 1, 12, 13, 30, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(5157)
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 25,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6485),
                            MovieId = 3,
                            ScreenNumber = 3,
                            StartsAt = new DateTime(2025, 1, 5, 8, 15, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6487)
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 27,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6490),
                            MovieId = 4,
                            ScreenNumber = 2,
                            StartsAt = new DateTime(2025, 5, 1, 8, 10, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6490)
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 84,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6491),
                            MovieId = 4,
                            ScreenNumber = 2,
                            StartsAt = new DateTime(2025, 6, 7, 4, 25, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6491)
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 63,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6492),
                            MovieId = 2,
                            ScreenNumber = 3,
                            StartsAt = new DateTime(2025, 2, 3, 7, 45, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6492)
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 25,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6503),
                            MovieId = 2,
                            ScreenNumber = 1,
                            StartsAt = new DateTime(2025, 5, 1, 8, 10, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6503)
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 65,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6504),
                            MovieId = 4,
                            ScreenNumber = 0,
                            StartsAt = new DateTime(2025, 6, 7, 4, 25, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6504)
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 48,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6505),
                            MovieId = 3,
                            ScreenNumber = 0,
                            StartsAt = new DateTime(2025, 2, 21, 18, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6505)
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 77,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6506),
                            MovieId = 2,
                            ScreenNumber = 4,
                            StartsAt = new DateTime(2025, 6, 7, 4, 25, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6506)
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 59,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6508),
                            MovieId = 3,
                            ScreenNumber = 4,
                            StartsAt = new DateTime(2025, 2, 21, 18, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6508)
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 87,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6508),
                            MovieId = 3,
                            ScreenNumber = 0,
                            StartsAt = new DateTime(2025, 1, 5, 8, 15, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6509)
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 99,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6509),
                            MovieId = 2,
                            ScreenNumber = 3,
                            StartsAt = new DateTime(2025, 1, 12, 13, 30, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6510)
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 45,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6510),
                            MovieId = 2,
                            ScreenNumber = 2,
                            StartsAt = new DateTime(2025, 2, 3, 7, 45, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6510)
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 38,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6511),
                            MovieId = 2,
                            ScreenNumber = 1,
                            StartsAt = new DateTime(2025, 8, 1, 11, 30, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6511)
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 26,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6512),
                            MovieId = 2,
                            ScreenNumber = 0,
                            StartsAt = new DateTime(2025, 6, 22, 13, 40, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6512)
                        },
                        new
                        {
                            Id = 16,
                            Capacity = 51,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6512),
                            MovieId = 2,
                            ScreenNumber = 4,
                            StartsAt = new DateTime(2025, 4, 2, 10, 5, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6513)
                        },
                        new
                        {
                            Id = 17,
                            Capacity = 74,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6513),
                            MovieId = 3,
                            ScreenNumber = 3,
                            StartsAt = new DateTime(2025, 6, 22, 13, 40, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6514)
                        },
                        new
                        {
                            Id = 18,
                            Capacity = 79,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6515),
                            MovieId = 2,
                            ScreenNumber = 0,
                            StartsAt = new DateTime(2025, 1, 12, 13, 30, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6515)
                        },
                        new
                        {
                            Id = 19,
                            Capacity = 40,
                            CreatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6516),
                            MovieId = 2,
                            ScreenNumber = 2,
                            StartsAt = new DateTime(2025, 1, 12, 13, 30, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 8, 25, 13, 15, 2, 535, DateTimeKind.Utc).AddTicks(6516)
                        });
                });

            modelBuilder.Entity("api_cinema_challenge.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ticket_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<int>("ScreeningId")
                        .HasColumnType("integer")
                        .HasColumnName("screening_id");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ScreeningId");

                    b.ToTable("tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 33,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 28,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 17,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 2,
                            ScreeningId = 6
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 41,
                            ScreeningId = 6
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = 42,
                            ScreeningId = 6
                        },
                        new
                        {
                            Id = 7,
                            CustomerId = 27,
                            ScreeningId = 13
                        },
                        new
                        {
                            Id = 8,
                            CustomerId = 39,
                            ScreeningId = 11
                        },
                        new
                        {
                            Id = 9,
                            CustomerId = 17,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 10,
                            CustomerId = 25,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 11,
                            CustomerId = 9,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 12,
                            CustomerId = 30,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 13,
                            CustomerId = 36,
                            ScreeningId = 6
                        },
                        new
                        {
                            Id = 14,
                            CustomerId = 41,
                            ScreeningId = 8
                        },
                        new
                        {
                            Id = 15,
                            CustomerId = 6,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 16,
                            CustomerId = 30,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 17,
                            CustomerId = 46,
                            ScreeningId = 16
                        },
                        new
                        {
                            Id = 18,
                            CustomerId = 21,
                            ScreeningId = 8
                        },
                        new
                        {
                            Id = 19,
                            CustomerId = 6,
                            ScreeningId = 3
                        },
                        new
                        {
                            Id = 20,
                            CustomerId = 47,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 21,
                            CustomerId = 40,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 22,
                            CustomerId = 28,
                            ScreeningId = 1
                        },
                        new
                        {
                            Id = 23,
                            CustomerId = 32,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 24,
                            CustomerId = 23,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 25,
                            CustomerId = 12,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 26,
                            CustomerId = 17,
                            ScreeningId = 11
                        },
                        new
                        {
                            Id = 27,
                            CustomerId = 18,
                            ScreeningId = 3
                        },
                        new
                        {
                            Id = 28,
                            CustomerId = 34,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 29,
                            CustomerId = 49,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 30,
                            CustomerId = 7,
                            ScreeningId = 13
                        },
                        new
                        {
                            Id = 31,
                            CustomerId = 42,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 32,
                            CustomerId = 14,
                            ScreeningId = 10
                        },
                        new
                        {
                            Id = 33,
                            CustomerId = 26,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 34,
                            CustomerId = 33,
                            ScreeningId = 17
                        },
                        new
                        {
                            Id = 35,
                            CustomerId = 21,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 36,
                            CustomerId = 44,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 37,
                            CustomerId = 28,
                            ScreeningId = 1
                        },
                        new
                        {
                            Id = 38,
                            CustomerId = 1,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 39,
                            CustomerId = 14,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 40,
                            CustomerId = 1,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 41,
                            CustomerId = 44,
                            ScreeningId = 17
                        },
                        new
                        {
                            Id = 42,
                            CustomerId = 29,
                            ScreeningId = 6
                        },
                        new
                        {
                            Id = 43,
                            CustomerId = 45,
                            ScreeningId = 17
                        },
                        new
                        {
                            Id = 44,
                            CustomerId = 37,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 45,
                            CustomerId = 35,
                            ScreeningId = 19
                        },
                        new
                        {
                            Id = 46,
                            CustomerId = 12,
                            ScreeningId = 16
                        },
                        new
                        {
                            Id = 47,
                            CustomerId = 44,
                            ScreeningId = 17
                        },
                        new
                        {
                            Id = 48,
                            CustomerId = 42,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 49,
                            CustomerId = 28,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 50,
                            CustomerId = 43,
                            ScreeningId = 8
                        },
                        new
                        {
                            Id = 51,
                            CustomerId = 26,
                            ScreeningId = 8
                        },
                        new
                        {
                            Id = 52,
                            CustomerId = 44,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 53,
                            CustomerId = 4,
                            ScreeningId = 19
                        },
                        new
                        {
                            Id = 54,
                            CustomerId = 22,
                            ScreeningId = 10
                        },
                        new
                        {
                            Id = 55,
                            CustomerId = 15,
                            ScreeningId = 3
                        },
                        new
                        {
                            Id = 56,
                            CustomerId = 43,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 57,
                            CustomerId = 43,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 58,
                            CustomerId = 9,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 59,
                            CustomerId = 15,
                            ScreeningId = 6
                        },
                        new
                        {
                            Id = 60,
                            CustomerId = 22,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 61,
                            CustomerId = 3,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 62,
                            CustomerId = 43,
                            ScreeningId = 16
                        },
                        new
                        {
                            Id = 63,
                            CustomerId = 7,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 64,
                            CustomerId = 27,
                            ScreeningId = 10
                        },
                        new
                        {
                            Id = 65,
                            CustomerId = 13,
                            ScreeningId = 17
                        },
                        new
                        {
                            Id = 66,
                            CustomerId = 39,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 67,
                            CustomerId = 47,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 68,
                            CustomerId = 21,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 69,
                            CustomerId = 46,
                            ScreeningId = 17
                        },
                        new
                        {
                            Id = 70,
                            CustomerId = 14,
                            ScreeningId = 1
                        },
                        new
                        {
                            Id = 71,
                            CustomerId = 28,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 72,
                            CustomerId = 47,
                            ScreeningId = 6
                        },
                        new
                        {
                            Id = 73,
                            CustomerId = 5,
                            ScreeningId = 17
                        },
                        new
                        {
                            Id = 74,
                            CustomerId = 11,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 75,
                            CustomerId = 46,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 76,
                            CustomerId = 45,
                            ScreeningId = 17
                        },
                        new
                        {
                            Id = 77,
                            CustomerId = 6,
                            ScreeningId = 1
                        },
                        new
                        {
                            Id = 78,
                            CustomerId = 16,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 79,
                            CustomerId = 36,
                            ScreeningId = 1
                        },
                        new
                        {
                            Id = 80,
                            CustomerId = 43,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 81,
                            CustomerId = 12,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 82,
                            CustomerId = 40,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 83,
                            CustomerId = 5,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 84,
                            CustomerId = 36,
                            ScreeningId = 10
                        },
                        new
                        {
                            Id = 85,
                            CustomerId = 21,
                            ScreeningId = 13
                        },
                        new
                        {
                            Id = 86,
                            CustomerId = 4,
                            ScreeningId = 10
                        },
                        new
                        {
                            Id = 87,
                            CustomerId = 42,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 88,
                            CustomerId = 1,
                            ScreeningId = 10
                        },
                        new
                        {
                            Id = 89,
                            CustomerId = 5,
                            ScreeningId = 1
                        },
                        new
                        {
                            Id = 90,
                            CustomerId = 34,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 91,
                            CustomerId = 35,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 92,
                            CustomerId = 47,
                            ScreeningId = 8
                        },
                        new
                        {
                            Id = 93,
                            CustomerId = 35,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 94,
                            CustomerId = 5,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 95,
                            CustomerId = 43,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 96,
                            CustomerId = 36,
                            ScreeningId = 1
                        },
                        new
                        {
                            Id = 97,
                            CustomerId = 4,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 98,
                            CustomerId = 31,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 99,
                            CustomerId = 25,
                            ScreeningId = 19
                        },
                        new
                        {
                            Id = 100,
                            CustomerId = 49,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 101,
                            CustomerId = 4,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 102,
                            CustomerId = 34,
                            ScreeningId = 10
                        },
                        new
                        {
                            Id = 103,
                            CustomerId = 14,
                            ScreeningId = 8
                        },
                        new
                        {
                            Id = 104,
                            CustomerId = 28,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 105,
                            CustomerId = 38,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 106,
                            CustomerId = 7,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 107,
                            CustomerId = 40,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 108,
                            CustomerId = 22,
                            ScreeningId = 3
                        },
                        new
                        {
                            Id = 109,
                            CustomerId = 4,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 110,
                            CustomerId = 34,
                            ScreeningId = 17
                        },
                        new
                        {
                            Id = 111,
                            CustomerId = 6,
                            ScreeningId = 6
                        },
                        new
                        {
                            Id = 112,
                            CustomerId = 9,
                            ScreeningId = 10
                        },
                        new
                        {
                            Id = 113,
                            CustomerId = 39,
                            ScreeningId = 8
                        },
                        new
                        {
                            Id = 114,
                            CustomerId = 22,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 115,
                            CustomerId = 26,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 116,
                            CustomerId = 34,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 117,
                            CustomerId = 15,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 118,
                            CustomerId = 41,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 119,
                            CustomerId = 39,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 120,
                            CustomerId = 14,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 121,
                            CustomerId = 10,
                            ScreeningId = 10
                        },
                        new
                        {
                            Id = 122,
                            CustomerId = 3,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 123,
                            CustomerId = 16,
                            ScreeningId = 10
                        },
                        new
                        {
                            Id = 124,
                            CustomerId = 3,
                            ScreeningId = 13
                        },
                        new
                        {
                            Id = 125,
                            CustomerId = 43,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 126,
                            CustomerId = 39,
                            ScreeningId = 16
                        },
                        new
                        {
                            Id = 127,
                            CustomerId = 6,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 128,
                            CustomerId = 20,
                            ScreeningId = 3
                        },
                        new
                        {
                            Id = 129,
                            CustomerId = 29,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 130,
                            CustomerId = 31,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 131,
                            CustomerId = 10,
                            ScreeningId = 6
                        },
                        new
                        {
                            Id = 132,
                            CustomerId = 16,
                            ScreeningId = 3
                        },
                        new
                        {
                            Id = 133,
                            CustomerId = 13,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 134,
                            CustomerId = 17,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 135,
                            CustomerId = 18,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 136,
                            CustomerId = 41,
                            ScreeningId = 19
                        },
                        new
                        {
                            Id = 137,
                            CustomerId = 41,
                            ScreeningId = 13
                        },
                        new
                        {
                            Id = 138,
                            CustomerId = 23,
                            ScreeningId = 3
                        },
                        new
                        {
                            Id = 139,
                            CustomerId = 40,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 140,
                            CustomerId = 38,
                            ScreeningId = 1
                        },
                        new
                        {
                            Id = 141,
                            CustomerId = 7,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 142,
                            CustomerId = 45,
                            ScreeningId = 6
                        },
                        new
                        {
                            Id = 143,
                            CustomerId = 30,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 144,
                            CustomerId = 14,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 145,
                            CustomerId = 14,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 146,
                            CustomerId = 23,
                            ScreeningId = 16
                        },
                        new
                        {
                            Id = 147,
                            CustomerId = 31,
                            ScreeningId = 16
                        },
                        new
                        {
                            Id = 148,
                            CustomerId = 45,
                            ScreeningId = 1
                        },
                        new
                        {
                            Id = 149,
                            CustomerId = 3,
                            ScreeningId = 6
                        },
                        new
                        {
                            Id = 150,
                            CustomerId = 1,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 151,
                            CustomerId = 35,
                            ScreeningId = 3
                        },
                        new
                        {
                            Id = 152,
                            CustomerId = 1,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 153,
                            CustomerId = 4,
                            ScreeningId = 8
                        },
                        new
                        {
                            Id = 154,
                            CustomerId = 25,
                            ScreeningId = 1
                        },
                        new
                        {
                            Id = 155,
                            CustomerId = 32,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 156,
                            CustomerId = 34,
                            ScreeningId = 13
                        },
                        new
                        {
                            Id = 157,
                            CustomerId = 33,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 158,
                            CustomerId = 24,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 159,
                            CustomerId = 31,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 160,
                            CustomerId = 44,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 161,
                            CustomerId = 37,
                            ScreeningId = 8
                        },
                        new
                        {
                            Id = 162,
                            CustomerId = 3,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 163,
                            CustomerId = 27,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 164,
                            CustomerId = 40,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 165,
                            CustomerId = 16,
                            ScreeningId = 10
                        },
                        new
                        {
                            Id = 166,
                            CustomerId = 26,
                            ScreeningId = 16
                        },
                        new
                        {
                            Id = 167,
                            CustomerId = 31,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 168,
                            CustomerId = 18,
                            ScreeningId = 11
                        },
                        new
                        {
                            Id = 169,
                            CustomerId = 30,
                            ScreeningId = 16
                        },
                        new
                        {
                            Id = 170,
                            CustomerId = 48,
                            ScreeningId = 11
                        },
                        new
                        {
                            Id = 171,
                            CustomerId = 30,
                            ScreeningId = 1
                        },
                        new
                        {
                            Id = 172,
                            CustomerId = 17,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 173,
                            CustomerId = 24,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 174,
                            CustomerId = 3,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 175,
                            CustomerId = 32,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 176,
                            CustomerId = 33,
                            ScreeningId = 10
                        },
                        new
                        {
                            Id = 177,
                            CustomerId = 48,
                            ScreeningId = 1
                        },
                        new
                        {
                            Id = 178,
                            CustomerId = 36,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 179,
                            CustomerId = 47,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 180,
                            CustomerId = 43,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 181,
                            CustomerId = 13,
                            ScreeningId = 1
                        },
                        new
                        {
                            Id = 182,
                            CustomerId = 19,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 183,
                            CustomerId = 35,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 184,
                            CustomerId = 37,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 185,
                            CustomerId = 28,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 186,
                            CustomerId = 11,
                            ScreeningId = 8
                        },
                        new
                        {
                            Id = 187,
                            CustomerId = 43,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 188,
                            CustomerId = 36,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 189,
                            CustomerId = 25,
                            ScreeningId = 19
                        },
                        new
                        {
                            Id = 190,
                            CustomerId = 40,
                            ScreeningId = 16
                        },
                        new
                        {
                            Id = 191,
                            CustomerId = 8,
                            ScreeningId = 17
                        },
                        new
                        {
                            Id = 192,
                            CustomerId = 23,
                            ScreeningId = 17
                        },
                        new
                        {
                            Id = 193,
                            CustomerId = 49,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 194,
                            CustomerId = 6,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 195,
                            CustomerId = 31,
                            ScreeningId = 3
                        },
                        new
                        {
                            Id = 196,
                            CustomerId = 16,
                            ScreeningId = 10
                        },
                        new
                        {
                            Id = 197,
                            CustomerId = 41,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 198,
                            CustomerId = 1,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 199,
                            CustomerId = 11,
                            ScreeningId = 15
                        });
                });

            modelBuilder.Entity("api_cinema_challenge.Models.Screening", b =>
                {
                    b.HasOne("api_cinema_challenge.Models.Movie", "Movie")
                        .WithMany("Screenings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("api_cinema_challenge.Models.Ticket", b =>
                {
                    b.HasOne("api_cinema_challenge.Models.Customer", "Customer")
                        .WithMany("Tickets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api_cinema_challenge.Models.Screening", "Screening")
                        .WithMany("Tickets")
                        .HasForeignKey("ScreeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Screening");
                });

            modelBuilder.Entity("api_cinema_challenge.Models.Customer", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("api_cinema_challenge.Models.Movie", b =>
                {
                    b.Navigation("Screenings");
                });

            modelBuilder.Entity("api_cinema_challenge.Models.Screening", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
