// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api_cinema_challenge.Data;

#nullable disable

namespace api_cinema_challenge.Migrations
{
    [DbContext(typeof(CinemaContext))]
    [Migration("20250822083522_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api_cinema_challenge.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "mick winfrey@gov.gr",
                            Name = "Mick Winfrey",
                            Phone = "52368274"
                        },
                        new
                        {
                            Id = 2,
                            Email = "charles winfrey@gov.nl",
                            Name = "Charles Winfrey",
                            Phone = "79181350"
                        },
                        new
                        {
                            Id = 3,
                            Email = "jimi hendrix@bbc.co.uk",
                            Name = "Jimi Hendrix",
                            Phone = "72502892"
                        },
                        new
                        {
                            Id = 4,
                            Email = "jimi hepburn@gov.ru",
                            Name = "Jimi Hepburn",
                            Phone = "15545519"
                        },
                        new
                        {
                            Id = 5,
                            Email = "audrey hepburn@theworld.ca",
                            Name = "Audrey Hepburn",
                            Phone = "92238414"
                        },
                        new
                        {
                            Id = 6,
                            Email = "kate trump@bbc.co.uk",
                            Name = "Kate Trump",
                            Phone = "86190574"
                        },
                        new
                        {
                            Id = 7,
                            Email = "kate obama@google.com",
                            Name = "Kate Obama",
                            Phone = "18975724"
                        },
                        new
                        {
                            Id = 8,
                            Email = "jimi winslet@gov.nl",
                            Name = "Jimi Winslet",
                            Phone = "92579632"
                        },
                        new
                        {
                            Id = 9,
                            Email = "mick hepburn@gov.ru",
                            Name = "Mick Hepburn",
                            Phone = "67334813"
                        },
                        new
                        {
                            Id = 10,
                            Email = "kate hendrix@tesla.com",
                            Name = "Kate Hendrix",
                            Phone = "82550950"
                        },
                        new
                        {
                            Id = 11,
                            Email = "oprah presley@gov.gr",
                            Name = "Oprah Presley",
                            Phone = "52997360"
                        },
                        new
                        {
                            Id = 12,
                            Email = "elvis hepburn@google.com",
                            Name = "Elvis Hepburn",
                            Phone = "64207390"
                        },
                        new
                        {
                            Id = 13,
                            Email = "oprah jagger@gov.gr",
                            Name = "Oprah Jagger",
                            Phone = "91111243"
                        },
                        new
                        {
                            Id = 14,
                            Email = "elvis hendrix@gov.us",
                            Name = "Elvis Hendrix",
                            Phone = "13823444"
                        },
                        new
                        {
                            Id = 15,
                            Email = "kate hepburn@gov.ru",
                            Name = "Kate Hepburn",
                            Phone = "97284220"
                        },
                        new
                        {
                            Id = 16,
                            Email = "mick jagger@bbc.co.uk",
                            Name = "Mick Jagger",
                            Phone = "28858754"
                        },
                        new
                        {
                            Id = 17,
                            Email = "elvis winfrey@gov.ru",
                            Name = "Elvis Winfrey",
                            Phone = "30038727"
                        },
                        new
                        {
                            Id = 18,
                            Email = "barack presley@tesla.com",
                            Name = "Barack Presley",
                            Phone = "99825705"
                        },
                        new
                        {
                            Id = 19,
                            Email = "kate hepburn@gov.nl",
                            Name = "Kate Hepburn",
                            Phone = "74139655"
                        },
                        new
                        {
                            Id = 20,
                            Email = "mick jagger@gov.us",
                            Name = "Mick Jagger",
                            Phone = "95805889"
                        },
                        new
                        {
                            Id = 21,
                            Email = "mick presley@something.com",
                            Name = "Mick Presley",
                            Phone = "48857519"
                        },
                        new
                        {
                            Id = 22,
                            Email = "charles jagger@gov.nl",
                            Name = "Charles Jagger",
                            Phone = "17920562"
                        },
                        new
                        {
                            Id = 23,
                            Email = "barack trump@tesla.com",
                            Name = "Barack Trump",
                            Phone = "26069406"
                        },
                        new
                        {
                            Id = 24,
                            Email = "kate winslet@gov.nl",
                            Name = "Kate Winslet",
                            Phone = "69787774"
                        },
                        new
                        {
                            Id = 25,
                            Email = "jimi obama@bbc.co.uk",
                            Name = "Jimi Obama",
                            Phone = "29989532"
                        },
                        new
                        {
                            Id = 26,
                            Email = "elvis obama@gov.nl",
                            Name = "Elvis Obama",
                            Phone = "44895432"
                        },
                        new
                        {
                            Id = 27,
                            Email = "oprah hepburn@gov.nl",
                            Name = "Oprah Hepburn",
                            Phone = "89556044"
                        },
                        new
                        {
                            Id = 28,
                            Email = "elvis windsor@gov.gr",
                            Name = "Elvis Windsor",
                            Phone = "60390346"
                        },
                        new
                        {
                            Id = 29,
                            Email = "charles windsor@theworld.ca",
                            Name = "Charles Windsor",
                            Phone = "44104543"
                        },
                        new
                        {
                            Id = 30,
                            Email = "donald hendrix@gov.ru",
                            Name = "Donald Hendrix",
                            Phone = "25105264"
                        },
                        new
                        {
                            Id = 31,
                            Email = "elvis obama@something.com",
                            Name = "Elvis Obama",
                            Phone = "52810651"
                        },
                        new
                        {
                            Id = 32,
                            Email = "barack winfrey@google.com",
                            Name = "Barack Winfrey",
                            Phone = "34881251"
                        },
                        new
                        {
                            Id = 33,
                            Email = "mick obama@tesla.com",
                            Name = "Mick Obama",
                            Phone = "36227999"
                        },
                        new
                        {
                            Id = 34,
                            Email = "oprah hepburn@tesla.com",
                            Name = "Oprah Hepburn",
                            Phone = "73319625"
                        },
                        new
                        {
                            Id = 35,
                            Email = "kate windsor@something.com",
                            Name = "Kate Windsor",
                            Phone = "61318402"
                        },
                        new
                        {
                            Id = 36,
                            Email = "audrey presley@tesla.com",
                            Name = "Audrey Presley",
                            Phone = "39504124"
                        },
                        new
                        {
                            Id = 37,
                            Email = "kate presley@google.com",
                            Name = "Kate Presley",
                            Phone = "16265734"
                        },
                        new
                        {
                            Id = 38,
                            Email = "donald hendrix@google.com",
                            Name = "Donald Hendrix",
                            Phone = "35991180"
                        },
                        new
                        {
                            Id = 39,
                            Email = "mick hepburn@bbc.co.uk",
                            Name = "Mick Hepburn",
                            Phone = "49117273"
                        },
                        new
                        {
                            Id = 40,
                            Email = "oprah winfrey@gov.ru",
                            Name = "Oprah Winfrey",
                            Phone = "72634505"
                        },
                        new
                        {
                            Id = 41,
                            Email = "jimi trump@gov.us",
                            Name = "Jimi Trump",
                            Phone = "96850307"
                        },
                        new
                        {
                            Id = 42,
                            Email = "jimi winslet@gov.gr",
                            Name = "Jimi Winslet",
                            Phone = "27324349"
                        },
                        new
                        {
                            Id = 43,
                            Email = "audrey jagger@tesla.com",
                            Name = "Audrey Jagger",
                            Phone = "91669517"
                        },
                        new
                        {
                            Id = 44,
                            Email = "audrey obama@nasa.org.us",
                            Name = "Audrey Obama",
                            Phone = "51414027"
                        },
                        new
                        {
                            Id = 45,
                            Email = "kate jagger@gov.us",
                            Name = "Kate Jagger",
                            Phone = "52606573"
                        },
                        new
                        {
                            Id = 46,
                            Email = "audrey obama@something.com",
                            Name = "Audrey Obama",
                            Phone = "41214230"
                        },
                        new
                        {
                            Id = 47,
                            Email = "kate obama@gov.us",
                            Name = "Kate Obama",
                            Phone = "11348879"
                        },
                        new
                        {
                            Id = 48,
                            Email = "audrey presley@something.com",
                            Name = "Audrey Presley",
                            Phone = "87270053"
                        },
                        new
                        {
                            Id = 49,
                            Email = "kate hendrix@tesla.com",
                            Name = "Kate Hendrix",
                            Phone = "36685672"
                        });
                });

            modelBuilder.Entity("api_cinema_challenge.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("movie_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rating");

                    b.Property<int>("RunTimeMins")
                        .HasColumnType("integer")
                        .HasColumnName("runtime_mins");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("movie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Very funny",
                            Rating = "years 16+",
                            RunTimeMins = 146,
                            Title = "The Transparent Flowers"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Very funny",
                            Rating = "years 6+",
                            RunTimeMins = 117,
                            Title = "Two Microscopic Houses"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Very funny",
                            Rating = "years 11+",
                            RunTimeMins = 129,
                            Title = "A herd of Orange Leopards"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Very funny",
                            Rating = "years 16+",
                            RunTimeMins = 80,
                            Title = "Several Microscopic Houses"
                        });
                });

            modelBuilder.Entity("api_cinema_challenge.Models.Screening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("screening_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer")
                        .HasColumnName("movie_id");

                    b.Property<int>("ScreenNumber")
                        .HasColumnType("integer")
                        .HasColumnName("screen_number");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("screenings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 67,
                            MovieId = 2,
                            ScreenNumber = 4,
                            StartsAt = new DateTime(2025, 6, 22, 13, 40, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 46,
                            MovieId = 3,
                            ScreenNumber = 4,
                            StartsAt = new DateTime(2025, 1, 5, 8, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 27,
                            MovieId = 2,
                            ScreenNumber = 1,
                            StartsAt = new DateTime(2025, 8, 1, 11, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 98,
                            MovieId = 3,
                            ScreenNumber = 0,
                            StartsAt = new DateTime(2025, 7, 19, 18, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 43,
                            MovieId = 3,
                            ScreenNumber = 3,
                            StartsAt = new DateTime(2025, 4, 18, 19, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 31,
                            MovieId = 1,
                            ScreenNumber = 4,
                            StartsAt = new DateTime(2025, 7, 3, 9, 55, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 66,
                            MovieId = 1,
                            ScreenNumber = 4,
                            StartsAt = new DateTime(2025, 3, 25, 15, 50, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 63,
                            MovieId = 1,
                            ScreenNumber = 2,
                            StartsAt = new DateTime(2025, 7, 3, 9, 55, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 47,
                            MovieId = 3,
                            ScreenNumber = 2,
                            StartsAt = new DateTime(2025, 4, 2, 10, 5, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 36,
                            MovieId = 2,
                            ScreenNumber = 4,
                            StartsAt = new DateTime(2025, 2, 3, 7, 45, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 81,
                            MovieId = 1,
                            ScreenNumber = 4,
                            StartsAt = new DateTime(2025, 3, 10, 6, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 28,
                            MovieId = 1,
                            ScreenNumber = 3,
                            StartsAt = new DateTime(2025, 2, 3, 7, 45, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 80,
                            MovieId = 1,
                            ScreenNumber = 4,
                            StartsAt = new DateTime(2025, 1, 5, 8, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 57,
                            MovieId = 1,
                            ScreenNumber = 4,
                            StartsAt = new DateTime(2025, 2, 21, 18, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 33,
                            MovieId = 3,
                            ScreenNumber = 2,
                            StartsAt = new DateTime(2025, 4, 2, 10, 5, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            Capacity = 94,
                            MovieId = 1,
                            ScreenNumber = 2,
                            StartsAt = new DateTime(2025, 2, 3, 7, 45, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            Capacity = 28,
                            MovieId = 2,
                            ScreenNumber = 2,
                            StartsAt = new DateTime(2025, 4, 2, 10, 5, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            Capacity = 52,
                            MovieId = 3,
                            ScreenNumber = 3,
                            StartsAt = new DateTime(2025, 8, 1, 11, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            Capacity = 75,
                            MovieId = 1,
                            ScreenNumber = 2,
                            StartsAt = new DateTime(2025, 2, 21, 18, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("api_cinema_challenge.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ticket_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<int>("ScreeningId")
                        .HasColumnType("integer")
                        .HasColumnName("screening_id");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ScreeningId");

                    b.ToTable("tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 43,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 1,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 40,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 10,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 26,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = 26,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 7,
                            CustomerId = 45,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 8,
                            CustomerId = 47,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 9,
                            CustomerId = 10,
                            ScreeningId = 11
                        },
                        new
                        {
                            Id = 10,
                            CustomerId = 31,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 11,
                            CustomerId = 43,
                            ScreeningId = 8
                        },
                        new
                        {
                            Id = 12,
                            CustomerId = 2,
                            ScreeningId = 3
                        },
                        new
                        {
                            Id = 13,
                            CustomerId = 18,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 14,
                            CustomerId = 15,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 15,
                            CustomerId = 29,
                            ScreeningId = 16
                        },
                        new
                        {
                            Id = 16,
                            CustomerId = 46,
                            ScreeningId = 8
                        },
                        new
                        {
                            Id = 17,
                            CustomerId = 30,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 18,
                            CustomerId = 3,
                            ScreeningId = 19
                        },
                        new
                        {
                            Id = 19,
                            CustomerId = 48,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 20,
                            CustomerId = 41,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 21,
                            CustomerId = 3,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 22,
                            CustomerId = 16,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 23,
                            CustomerId = 14,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 24,
                            CustomerId = 39,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 25,
                            CustomerId = 7,
                            ScreeningId = 19
                        },
                        new
                        {
                            Id = 26,
                            CustomerId = 32,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 27,
                            CustomerId = 35,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 28,
                            CustomerId = 22,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 29,
                            CustomerId = 21,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 30,
                            CustomerId = 2,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 31,
                            CustomerId = 44,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 32,
                            CustomerId = 42,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 33,
                            CustomerId = 48,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 34,
                            CustomerId = 5,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 35,
                            CustomerId = 37,
                            ScreeningId = 16
                        },
                        new
                        {
                            Id = 36,
                            CustomerId = 37,
                            ScreeningId = 10
                        },
                        new
                        {
                            Id = 37,
                            CustomerId = 5,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 38,
                            CustomerId = 9,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 39,
                            CustomerId = 10,
                            ScreeningId = 3
                        },
                        new
                        {
                            Id = 40,
                            CustomerId = 21,
                            ScreeningId = 16
                        },
                        new
                        {
                            Id = 41,
                            CustomerId = 5,
                            ScreeningId = 17
                        },
                        new
                        {
                            Id = 42,
                            CustomerId = 11,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 43,
                            CustomerId = 49,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 44,
                            CustomerId = 30,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 45,
                            CustomerId = 45,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 46,
                            CustomerId = 18,
                            ScreeningId = 19
                        },
                        new
                        {
                            Id = 47,
                            CustomerId = 27,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 48,
                            CustomerId = 38,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 49,
                            CustomerId = 1,
                            ScreeningId = 16
                        },
                        new
                        {
                            Id = 50,
                            CustomerId = 34,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 51,
                            CustomerId = 4,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 52,
                            CustomerId = 33,
                            ScreeningId = 11
                        },
                        new
                        {
                            Id = 53,
                            CustomerId = 7,
                            ScreeningId = 19
                        },
                        new
                        {
                            Id = 54,
                            CustomerId = 14,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 55,
                            CustomerId = 49,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 56,
                            CustomerId = 8,
                            ScreeningId = 11
                        },
                        new
                        {
                            Id = 57,
                            CustomerId = 43,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 58,
                            CustomerId = 32,
                            ScreeningId = 6
                        },
                        new
                        {
                            Id = 59,
                            CustomerId = 40,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 60,
                            CustomerId = 38,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 61,
                            CustomerId = 29,
                            ScreeningId = 3
                        },
                        new
                        {
                            Id = 62,
                            CustomerId = 24,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 63,
                            CustomerId = 11,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 64,
                            CustomerId = 6,
                            ScreeningId = 13
                        },
                        new
                        {
                            Id = 65,
                            CustomerId = 4,
                            ScreeningId = 13
                        },
                        new
                        {
                            Id = 66,
                            CustomerId = 42,
                            ScreeningId = 8
                        },
                        new
                        {
                            Id = 67,
                            CustomerId = 48,
                            ScreeningId = 16
                        },
                        new
                        {
                            Id = 68,
                            CustomerId = 15,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 69,
                            CustomerId = 18,
                            ScreeningId = 13
                        },
                        new
                        {
                            Id = 70,
                            CustomerId = 9,
                            ScreeningId = 19
                        },
                        new
                        {
                            Id = 71,
                            CustomerId = 47,
                            ScreeningId = 6
                        },
                        new
                        {
                            Id = 72,
                            CustomerId = 36,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 73,
                            CustomerId = 46,
                            ScreeningId = 6
                        },
                        new
                        {
                            Id = 74,
                            CustomerId = 27,
                            ScreeningId = 19
                        },
                        new
                        {
                            Id = 75,
                            CustomerId = 21,
                            ScreeningId = 19
                        },
                        new
                        {
                            Id = 76,
                            CustomerId = 13,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 77,
                            CustomerId = 9,
                            ScreeningId = 13
                        },
                        new
                        {
                            Id = 78,
                            CustomerId = 1,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 79,
                            CustomerId = 5,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 80,
                            CustomerId = 35,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 81,
                            CustomerId = 43,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 82,
                            CustomerId = 1,
                            ScreeningId = 10
                        },
                        new
                        {
                            Id = 83,
                            CustomerId = 26,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 84,
                            CustomerId = 47,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 85,
                            CustomerId = 3,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 86,
                            CustomerId = 35,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 87,
                            CustomerId = 6,
                            ScreeningId = 19
                        },
                        new
                        {
                            Id = 88,
                            CustomerId = 7,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 89,
                            CustomerId = 12,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 90,
                            CustomerId = 12,
                            ScreeningId = 19
                        },
                        new
                        {
                            Id = 91,
                            CustomerId = 7,
                            ScreeningId = 17
                        },
                        new
                        {
                            Id = 92,
                            CustomerId = 8,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 93,
                            CustomerId = 19,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 94,
                            CustomerId = 22,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 95,
                            CustomerId = 2,
                            ScreeningId = 16
                        },
                        new
                        {
                            Id = 96,
                            CustomerId = 2,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 97,
                            CustomerId = 13,
                            ScreeningId = 8
                        },
                        new
                        {
                            Id = 98,
                            CustomerId = 4,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 99,
                            CustomerId = 12,
                            ScreeningId = 11
                        },
                        new
                        {
                            Id = 100,
                            CustomerId = 5,
                            ScreeningId = 6
                        },
                        new
                        {
                            Id = 101,
                            CustomerId = 16,
                            ScreeningId = 16
                        },
                        new
                        {
                            Id = 102,
                            CustomerId = 5,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 103,
                            CustomerId = 45,
                            ScreeningId = 8
                        },
                        new
                        {
                            Id = 104,
                            CustomerId = 23,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 105,
                            CustomerId = 15,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 106,
                            CustomerId = 43,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 107,
                            CustomerId = 45,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 108,
                            CustomerId = 28,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 109,
                            CustomerId = 31,
                            ScreeningId = 17
                        },
                        new
                        {
                            Id = 110,
                            CustomerId = 32,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 111,
                            CustomerId = 36,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 112,
                            CustomerId = 41,
                            ScreeningId = 16
                        },
                        new
                        {
                            Id = 113,
                            CustomerId = 22,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 114,
                            CustomerId = 26,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 115,
                            CustomerId = 29,
                            ScreeningId = 1
                        },
                        new
                        {
                            Id = 116,
                            CustomerId = 19,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 117,
                            CustomerId = 18,
                            ScreeningId = 11
                        },
                        new
                        {
                            Id = 118,
                            CustomerId = 16,
                            ScreeningId = 19
                        },
                        new
                        {
                            Id = 119,
                            CustomerId = 7,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 120,
                            CustomerId = 1,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 121,
                            CustomerId = 36,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 122,
                            CustomerId = 39,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 123,
                            CustomerId = 13,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 124,
                            CustomerId = 13,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 125,
                            CustomerId = 25,
                            ScreeningId = 13
                        },
                        new
                        {
                            Id = 126,
                            CustomerId = 31,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 127,
                            CustomerId = 18,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 128,
                            CustomerId = 42,
                            ScreeningId = 3
                        },
                        new
                        {
                            Id = 129,
                            CustomerId = 9,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 130,
                            CustomerId = 44,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 131,
                            CustomerId = 6,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 132,
                            CustomerId = 18,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 133,
                            CustomerId = 39,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 134,
                            CustomerId = 13,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 135,
                            CustomerId = 36,
                            ScreeningId = 17
                        },
                        new
                        {
                            Id = 136,
                            CustomerId = 15,
                            ScreeningId = 1
                        },
                        new
                        {
                            Id = 137,
                            CustomerId = 35,
                            ScreeningId = 6
                        },
                        new
                        {
                            Id = 138,
                            CustomerId = 28,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 139,
                            CustomerId = 16,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 140,
                            CustomerId = 39,
                            ScreeningId = 11
                        },
                        new
                        {
                            Id = 141,
                            CustomerId = 7,
                            ScreeningId = 8
                        },
                        new
                        {
                            Id = 142,
                            CustomerId = 38,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 143,
                            CustomerId = 2,
                            ScreeningId = 16
                        },
                        new
                        {
                            Id = 144,
                            CustomerId = 24,
                            ScreeningId = 6
                        },
                        new
                        {
                            Id = 145,
                            CustomerId = 42,
                            ScreeningId = 13
                        },
                        new
                        {
                            Id = 146,
                            CustomerId = 6,
                            ScreeningId = 8
                        },
                        new
                        {
                            Id = 147,
                            CustomerId = 26,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 148,
                            CustomerId = 40,
                            ScreeningId = 13
                        },
                        new
                        {
                            Id = 149,
                            CustomerId = 16,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 150,
                            CustomerId = 21,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 151,
                            CustomerId = 6,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 152,
                            CustomerId = 11,
                            ScreeningId = 1
                        },
                        new
                        {
                            Id = 153,
                            CustomerId = 19,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 154,
                            CustomerId = 20,
                            ScreeningId = 6
                        },
                        new
                        {
                            Id = 155,
                            CustomerId = 34,
                            ScreeningId = 10
                        },
                        new
                        {
                            Id = 156,
                            CustomerId = 41,
                            ScreeningId = 2
                        },
                        new
                        {
                            Id = 157,
                            CustomerId = 42,
                            ScreeningId = 19
                        },
                        new
                        {
                            Id = 158,
                            CustomerId = 27,
                            ScreeningId = 17
                        },
                        new
                        {
                            Id = 159,
                            CustomerId = 46,
                            ScreeningId = 1
                        },
                        new
                        {
                            Id = 160,
                            CustomerId = 5,
                            ScreeningId = 13
                        },
                        new
                        {
                            Id = 161,
                            CustomerId = 2,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 162,
                            CustomerId = 39,
                            ScreeningId = 17
                        },
                        new
                        {
                            Id = 163,
                            CustomerId = 20,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 164,
                            CustomerId = 5,
                            ScreeningId = 8
                        },
                        new
                        {
                            Id = 165,
                            CustomerId = 1,
                            ScreeningId = 6
                        },
                        new
                        {
                            Id = 166,
                            CustomerId = 14,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 167,
                            CustomerId = 35,
                            ScreeningId = 10
                        },
                        new
                        {
                            Id = 168,
                            CustomerId = 32,
                            ScreeningId = 3
                        },
                        new
                        {
                            Id = 169,
                            CustomerId = 6,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 170,
                            CustomerId = 24,
                            ScreeningId = 8
                        },
                        new
                        {
                            Id = 171,
                            CustomerId = 10,
                            ScreeningId = 8
                        },
                        new
                        {
                            Id = 172,
                            CustomerId = 5,
                            ScreeningId = 16
                        },
                        new
                        {
                            Id = 173,
                            CustomerId = 19,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 174,
                            CustomerId = 27,
                            ScreeningId = 8
                        },
                        new
                        {
                            Id = 175,
                            CustomerId = 39,
                            ScreeningId = 1
                        },
                        new
                        {
                            Id = 176,
                            CustomerId = 49,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 177,
                            CustomerId = 34,
                            ScreeningId = 10
                        },
                        new
                        {
                            Id = 178,
                            CustomerId = 38,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 179,
                            CustomerId = 47,
                            ScreeningId = 11
                        },
                        new
                        {
                            Id = 180,
                            CustomerId = 22,
                            ScreeningId = 14
                        },
                        new
                        {
                            Id = 181,
                            CustomerId = 32,
                            ScreeningId = 15
                        },
                        new
                        {
                            Id = 182,
                            CustomerId = 23,
                            ScreeningId = 19
                        },
                        new
                        {
                            Id = 183,
                            CustomerId = 3,
                            ScreeningId = 18
                        },
                        new
                        {
                            Id = 184,
                            CustomerId = 8,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 185,
                            CustomerId = 1,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 186,
                            CustomerId = 16,
                            ScreeningId = 19
                        },
                        new
                        {
                            Id = 187,
                            CustomerId = 3,
                            ScreeningId = 11
                        },
                        new
                        {
                            Id = 188,
                            CustomerId = 28,
                            ScreeningId = 3
                        },
                        new
                        {
                            Id = 189,
                            CustomerId = 34,
                            ScreeningId = 13
                        },
                        new
                        {
                            Id = 190,
                            CustomerId = 1,
                            ScreeningId = 6
                        },
                        new
                        {
                            Id = 191,
                            CustomerId = 26,
                            ScreeningId = 8
                        },
                        new
                        {
                            Id = 192,
                            CustomerId = 14,
                            ScreeningId = 5
                        },
                        new
                        {
                            Id = 193,
                            CustomerId = 37,
                            ScreeningId = 11
                        },
                        new
                        {
                            Id = 194,
                            CustomerId = 13,
                            ScreeningId = 11
                        },
                        new
                        {
                            Id = 195,
                            CustomerId = 46,
                            ScreeningId = 4
                        },
                        new
                        {
                            Id = 196,
                            CustomerId = 49,
                            ScreeningId = 12
                        },
                        new
                        {
                            Id = 197,
                            CustomerId = 45,
                            ScreeningId = 7
                        },
                        new
                        {
                            Id = 198,
                            CustomerId = 25,
                            ScreeningId = 9
                        },
                        new
                        {
                            Id = 199,
                            CustomerId = 6,
                            ScreeningId = 15
                        });
                });

            modelBuilder.Entity("api_cinema_challenge.Models.Screening", b =>
                {
                    b.HasOne("api_cinema_challenge.Models.Movie", "Movie")
                        .WithMany("Screenings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("api_cinema_challenge.Models.Ticket", b =>
                {
                    b.HasOne("api_cinema_challenge.Models.Customer", "Customer")
                        .WithMany("Tickets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api_cinema_challenge.Models.Screening", "Screening")
                        .WithMany("Tickets")
                        .HasForeignKey("ScreeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Screening");
                });

            modelBuilder.Entity("api_cinema_challenge.Models.Customer", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("api_cinema_challenge.Models.Movie", b =>
                {
                    b.Navigation("Screenings");
                });

            modelBuilder.Entity("api_cinema_challenge.Models.Screening", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
